### ISSUE TITLE
Correctly handle non-premium Spotify members

### ISSUE THREAD

**Issue by rhg1** [RiceComp413-Fall2022/Jukebox#56]
Still lets you go to primary page with non-premium spotify login but then search doesn't work and no songs are displayed in the queue.

**Comment by aedancullen** [comment]
Do we need primary to work with non-premium Spotify?

**Comment by tmahesh04** [comment]
There is no easy way to check whether the person has a spotify account before they are in the player. I can add an alert when they try to add something to the track and say "need spotify premium account"
